package com.riskplatform.common.enums;

public enum EventType {
    TRANSACTION_RECEIVED,
    TRANSACTION_VALIDATED,
    TRANSACTION_REJECTED,
    FRAUD_ALERT_RAISED,
    FRAUD_ALERT_CONFIRMED,
    FRAUD_ALERT_DISMISSED,
    COMPLIANCE_CHECK_COMPLETED,
    CTR_REPORT_REQUIRED,
    SAR_REPORT_REQUIRED,
    SANCTIONS_HIT_DETECTED,
    KYC_VERIFICATION_REQUIRED,
    MANUAL_REVIEW_REQUIRED,
    TRANSACTION_APPROVED,
    TRANSACTION_BLOCKED,
    RISK_SCORE_CALCULATED,
    RISK_PROFILE_UPDATED,
    RISK_ALERT_HIGH_SCORE,
    NOTIFICATION_SENT
}
