package com.riskplatform.common.enums;

public enum SagaStatus {
    INITIATED,
    IN_PROGRESS,
    RISK_ASSESSMENT_PENDING,
    RISK_ASSESSMENT_COMPLETED,
    RISK_ASSESSMENT_TIMEOUT,
    FRAUD_DETECTION_PENDING,
    FRAUD_DETECTION_COMPLETED,
    FRAUD_DETECTION_FAILED,
    FRAUD_DETECTION_TIMEOUT,
    COMPLIANCE_CHECK_PENDING,
    COMPLIANCE_CHECK_COMPLETED,
    COMPLIANCE_FAILED,
    AUTO_APPROVED,
    MANUAL_REVIEW_REQUIRED,
    BLOCKED,
    COMPENSATING,
    COMPENSATED,
    ESCALATED_MANUAL_REVIEW,
    TERMINATED,
    APPROVED,
    REJECTED,
    FAILED,
    COMPLETED,
    FORCE_APPROVED
}
