package com.transaction.orchestration.service.model;

public enum SagaStatus {
    INITIATED,
    RISK_ASSESSMENT_PENDING,
    RISK_ASSESSMENT_COMPLETED,
    RISK_ASSESSMENT_TIMEOUT,
    FRAUD_DETECTION_PENDING,
    FRAUD_DETECTION_COMPLETED,
    FRAUD_DETECTION_TIMEOUT,
    COMPLIANCE_CHECK_PENDING,
    COMPLIANCE_CHECK_COMPLETED,
    COMPLIANCE_FAILED,
    AUTO_APPROVED,
    MANUAL_REVIEW_REQUIRED,
    REVIEW_REQUIRED,
    BLOCKED,
    COMPENSATING,
    COMPENSATED,
    ESCALATED_MANUAL_REVIEW,
    TERMINATED,
    APPROVED,
    REJECTED,
    FAILED,
    ESCALATED
}